title = 'TOML Example'

[general]
usecudnn = false
usecudnnbenchmark = false
gpuid = 1
loadpretrainedmodel = false
pretrainedmodelpath = 'trainedmodel.pt'
savemodel = false

[input]
batchsize = 32
numworkers = 18
shuffle = true

[model]
embeddeddimension = 200
strlenmax = 15
filterwidth = 1
filterchannel = 130
layersize = 2
inception = true
distance = 'cosine'

[training]
model = '2'
epochs = 30
startepoch = 0
dataset = 'sample_data/'
learningrate = 0.01
weightdecay = 0.0001